### ISSUE TITLE
Switch mvICA  to dependency

### ISSUE THREAD

**Issue by rflperry** [mvlearn/mvlearn#214]
Move Multiview ICA to being a pip dependency (https://github.com/hugorichard/multiviewica) w/ wrapper function.

**Comment by gmischl1** [comment]
This might be restrictive for the conda installation, since multiviewica isn't available on conda-forge

**Comment by pierreablin** [comment]
The code for mvica is still in a very early stage, and will very likely change. I think we will ultimately move the code to this repository.
