### ISSUE TITLE
Minimal requirements do not work

### ISSUE THREAD

**Issue by pierreablin** [mvlearn/mvlearn#219]
I tried to run mvlearn with scikit-learn 0.20.1 and scipy 1.2.1, which are both >= the requirements, which lead to import errors in graspy:

```
~/anaconda3/lib/python3.7/site-packages/graspy/cluster/autogmm.py in <module>
     18 from sklearn.metrics import adjusted_rand_score
     19 from sklearn.mixture import GaussianMixture
---> 20 from sklearn.mixture._gaussian_mixture import (
     21     _compute_precision_cholesky,
     22     _estimate_gaussian_parameters,

ModuleNotFoundError: No module named 'sklearn.mixture._gaussian_mixture'
```

and in hyppo

```
~/anaconda3/lib/python3.7/site-packages/hyppo/independence/mgc.py in <module>
      1 import warnings
----> 2 from scipy.stats import multiscale_graphcorr
      3 
      4 from .._utils import euclidean, check_xy_distmat
      5 from .base import IndependenceTest

ImportError: cannot import name 'multiscale_graphcorr' from 'scipy.stats' (/home/pierre/anaconda3/lib/python3.7/site-packages/scipy/stats/__init__.py)
```
updating both packages to their last version fixed the problem.

I understand that these issues come from the dependencies rather than core mvlearn, but I think it would be better to havenewer version of the packages in requirement.txt

**Comment by rflperry** [comment]
Are you certain that your sci-kit learn was >= 0.19.1? The _gaussian_mixture module I believe was added in 0.18 and graspy has that as their minimal requirement.
