### ISSUE TITLE
Add groupPCA

### ISSUE THREAD

**Issue by pierreablin** [mvlearn/mvlearn#224]
Hi,

I'm working on a PR to implement groupPCA, and before I send a first draft, I have a few questions:

### Should we rely on sklearn for the usual PCA?

+: bullet proof code, handles big datasets with randomized PCA
-: always subtract the average to the signals, which is usually not what you want to do when processing some signals (like M/EEG)

### Transform API

In its original form, GroupPCA (like groupICA) takes multiple datasets Xs and returns only one dataset X (*not* a list), this does not break the API of mvlearn, right?

I'm thinking about adding a parameter which makes `transform` return multiple datasets, what do you think?

@agramfort

**Comment by rflperry** [comment]
1. We can always rely on numpy svd to do an uncentered PCA if the need arises, no?
2. I don't believe that we specified in `transform` outputs in our API. As is, we typically are returning a list of transformed views. For groupICA, I defined transform to return a list of recovered sources (applying the unmixing matrices to each view) as done in the single view sklearn fastICA.
3. For groupPCA, the output that makes sense is a single view, but I agree that I think a parameter should allow `transform` to return a list of that single view duplicated for each input view. Whether we want that output to be the default, and update the API to state a list as the default output so is an open question.

**Comment by pierreablin** [comment]
1. Indeed, so far I'll stick to sklearn for simplicity, but we can add this option latter if need be.
2. Ok :+1: 
3. I was more thinking about least squares estimates per view:

if you say that Z is single subject transform the transform of Xs[i] is Zs[i] = Xs[i].dot(W), where W  minimizes the difference between Zs[i] and Z. I don't know if it makes sense; I think I've seen this in some paper, but can't remember which.

**Comment by agramfort** [comment]
Xs = est.transform(Xs)

seem the expected behavior

>

**Comment by pierreablin** [comment]
See the #225 PR :)
