### ISSUE TITLE
Switch to sphinx-gallery

### ISSUE THREAD

**Issue by rflperry** [mvlearn/mvlearn#231]
## Enhancement
Use `.py` examples and tutorials and [sphinx gallery](https://sphinx-gallery.github.io/stable/index.html) to render them in the webdocs.

## Current Behavior
`docs/tutorials` contains `.ipynb` notebook tutorials that are rendered in the tutorials sidebar section.

**Comment by agramfort** [comment]
I can take a stab at this. @rflperry I need admin access to this repo so I can activate circleci. Next I would setup ssh keys etc so the doc is pushed automatically in http://mvlearn.github.io

**Comment by rflperry** [comment]
Thanks! access granted. Are we switching to [http://mvlearn.github.io](http://mvlearn.github.io) from [https://mvlearn.neurodata.io/](https://mvlearn.neurodata.io/)? Fine by us. I can help out with ssh keys either way but it's new to me.

**Comment by agramfort** [comment]
yes I would move to https://mvlearn.github.io/

>

**Comment by agramfort** [comment]
can you activate circleci?

>

**Comment by agramfort** [comment]
I think I need to org admin to do it. Or you make me org admin

>

**Comment by agramfort** [comment]
can you go to
https://app.circleci.com/projects/project-dashboard/github/mvlearn/ and
activate it?

>

**Comment by agramfort** [comment]
we need also a repo https://github.com/mvlearn/mvlearn.github.io

>

**Comment by rflperry** [comment]
repo [https://github.com/mvlearn/mvlearn.github.io](https://github.com/mvlearn/mvlearn.github.io) added. Does it need to be covered by circle.io? Let me know if you still don't have necessary access to anything.

**Comment by rflperry** [comment]
You have ownership privileges on the org now so that should cover all permissions.

**Comment by rflperry** [comment]
Now it's just a matter of hosting the linking circleci with mvlearn.github.io?

**Comment by agramfort** [comment]
I need to fix mvlearn.github.io so it gets filled by circleci at each commit

>

**Comment by rflperry** [comment]
I'm going to start looking syncing circleci to fill mvearl.github.io if you have any pointers @agramfort

**Comment by agramfort** [comment]
see the end of my circleci config.

I did it for these projects https://github.com/PythonOT/ and
https://github.com/braindecode/braindecode

**Comment by rflperry** [comment]
https://mvlearn.github.io/ up and running. ssh fingerprint needed in the config.yml for the write key to be added to the circleci container.

**Comment by agramfort** [comment]
great job !

>
