### ISSUE TITLE
Add cross validation easily

### ISSUE THREAD

**Issue by pierreablin** [mvlearn/mvlearn#233]
Hi,

Now that we can smoothly integrate `mvlearn`in sklearn pipelines, it would be awesome to have cross validation working. Using `sklearn.model_selection.cross_validate` in `cross_validate(estimator, Xs, y)` will return an error, since the train-test split performed under the hood errors when provided with multiview data.

I'm wondering what would be the best way to proceed: do we have to copy some of sklearn's code, or is there a smarter way to do?

**Comment by rflperry** [comment]
Could `Xs` be inputted in a concatenated form (say with `ConcatTransformer`) and `estimator` is a pipeline that does the `inverse_transform` followed by `predict`. Then you can input those to `cross_validate` and get your answer. A wrapper could handle all of those steps, either an `mvlearn` `cross_validate` could be written or a generic function that handles any inputted `sklearn.model_selection` function.

**Comment by pierreablin** [comment]
It works fine @rflperry :) But I suspect we need to implement some `Splitters` (or whatever the name is) that split single datasets into single views.

**Comment by pierreablin** [comment]
> @pierreablin is the `inverse_transform` not the splitter functionality we desire? Since we effectively merge->sklearn->split (based on merge).

Yes but I don't think we can make pipeline understand that it needs to use inverse_transform when calling .transform ? Not sure about this.
