### ISSUE TITLE
Transpose mv_ica and perm_ica umixing matrix

### ISSUE THREAD

**Issue by rflperry** [mvlearn/mvlearn#244]
`GroupICA` has unmixing matrices (`self.individual_components_`) such that XW^T recovers the source. `PermICA` and `MultiviewICA` have the unmixing matrix such that XW recovers the source (as I had initially implemented it). `GroupICA` version I believe is correct and the latter two should be switched.

Multiview ICA tutorial should be updated as well.

**Comment by hugorichard** [comment]
I'll take this issue.
I'll also update the code so that there is no difference with 
https://github.com/hugorichard/multiviewica
so that I can delete this repository as it is a duplicate.

**Comment by rflperry** [comment]
great thanks!

**Comment by hugorichard** [comment]
The attribute .source_ depends on the number of samples. Is there any reason for this choice ? I am not sure this is a good practice.

**Comment by agramfort** [comment]
+1 for not having attributes whose size depends on n_samples

it appears in sklearn but it's for (bad) historical reasons

>

**Comment by rflperry** [comment]
@hugorichard I reformatted the code to reflect the sklearn fastICA as best I could, which may have led to this issue. I take no issue with removing it as an attribute.

**Comment by rflperry** [comment]
@hugorichard I can make a PR for this if you are currently busy with other things

**Comment by hugorichard** [comment]
Sorry I will hurry up. I decided to rewrite the code so that it is more similar to the GroupPCA and GroupICA one and I have to spend more time on it. I'll make a sprint on this next Friday.
