### ISSUE TITLE
Add MCCA module

### ISSUE THREAD

**Issue by idc9** [mvlearn/mvlearn#247]
Add a new multi-CCA module by incorporating the mcca module from https://github.com/idc9/mvdr into mvlearn. This package implements a generalized eigenvector formulation of MCCA by extending SUMCORR-AVGVAR to (optionally) include regularization and kernels (see https://github.com/idc9/mvdr/blob/main/docs/mcca_gevp_docs.pdf).

**Comment by rflperry** [comment]
Solved by #249
