### ISSUE TITLE
DCCA

### ISSUE THREAD

**Issue by sunshiding** [mvlearn/mvlearn#254]
When I run the DCCA script in the document, I encountered some problems. The error is as follows:

---------------------------------------------------------------------------
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-806b2b5fa5de> in <module>
      7             layer_sizes1=layers1, layer_sizes2=layers2, epoch_num=5)
      8 
----> 9 dcca.fit(Xs_train)
     10 Xs_transformed = dcca.transform(Xs_test)

/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/mvlearn/mvlearn/embed/dcca.py in fit(self, Xs, y)
    677                 batch_x1 = x1[batch_idx, :]
    678                 batch_x2 = x2[batch_idx, :]
--> 679                 o1, o2 = self.model_(batch_x1, batch_x2)
    680                 loss = self.loss_(o1, o2)
    681                 train_losses.append(loss.item())

/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

/home/jovyan/.pyenv/versions/3.7.4/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py in forward(self, *inputs, **kwargs)
    147                 raise RuntimeError("module must have its parameters and buffers "
    148                                    "on device {} (device_ids[0]) but found one of "
--> 149                                    "them on device: {}".format(self.src_device_obj, t.device))
    150 
    151         inputs, kwargs = self.scatter(inputs, kwargs, self.device_ids)

RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

AttributeError: 'DCCA' object has no attribute 'to'

Then I tried to use the command: pip install mvlearn[torch]. Still get this error.

**Comment by rflperry** [comment]
It appears that torch is installed correctly, so that's good. How did you instantiate `DCCA`? Are you attempting to use a gpu?

**Comment by gavinmischler** [comment]
Also, just to clarify since we recently changed the documentation site, are you trying to run the DCCA example on the new site?https://mvlearn.github.io/auto_examples/embed/plot_dcca_tutorial.html#sphx-glr-auto-examples-embed-plot-dcca-tutorial-py

**Comment by sunshiding** [comment]
> It appears that torch is installed correctly, so that's good. How did you instantiate `DCCA`? Are you attempting to use a gpu?

Sorry, I made a mistake. I installed the GPU version of mvlearn, but forgot to set the device id during training.

**Comment by sunshiding** [comment]
> Also, just to clarify since we recently changed the documentation site, are you trying to run the DCCA example on the new site?https://mvlearn.github.io/auto_examples/embed/plot_dcca_tutorial.html#sphx-glr-auto-examples-embed-plot-dcca-tutorial-py

Sorry, I made a mistake. I installed the GPU version of mvlearn, but forgot to set the device id during training.

**Comment by rflperry** [comment]
Seems resolved
