### ISSUE TITLE
Gau

### ISSUE THREAD

**Issue by lkrmbhlz** [mvlearn/mvlearn#296]
## Expected Behavior
Execute 

```
m_spectral1 = MultiviewCoRegSpectralClustering(n_clusters=n_class, random_state=RANDOM_SEED, n_init=100)
m_clusters1 = m_spectral1.fit_predict(Xs)
```

with scikit-learn version 0.24.2.

## Actual Behavior
I get a "ModuleNotFoundError: No module named 'sklearn.mixture.gaussian_mixture'" error.

This is because the sklearn.mixture.gaussian_mixture module is  deprecated in version 0.22 and removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.mixture. Anything that cannot be imported from sklearn.mixture is now part of the private API.

## Template Code
```mvlearn
from mvlearn.cluster import MultiviewCoRegSpectralClustering
from mvlearn.datasets import load_UCImultifeature

n_class = 5
Xs, labels = load_UCImultifeature(
    select_labeled=list(range(n_class)), views=[0, 1])

m_spectral1 = MultiviewCoRegSpectralClustering(n_clusters=n_class,
                                               random_state=RANDOM_SEED,
                                               n_init=100)
m_clusters1 = m_spectral1.fit_predict(Xs)

```

## Full Traceback
```pytb
(untitled1) C:\Users\user\PycharmProjects\untitled1\test>python test.py
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from mvlearn.cluster import MultiviewCoRegSpectralClustering
  File "C:\Users\user\Miniconda3\envs\untitled1\lib\site-packages\mvlearn\__init__.py", line 1, in <module>
    import mvlearn.embed
  File "C:\Users\user\Miniconda3\envs\untitled1\lib\site-packages\mvlearn\embed\__init__.py", line 2, in <module>
    from .omnibus import Omnibus
  File "C:\Users\user\Miniconda3\envs\untitled1\lib\site-packages\mvlearn\embed\omnibus.py", line 19, in <module>
    from graspy.embed import OmnibusEmbed
  File "C:\Users\user\Miniconda3\envs\untitled1\lib\site-packages\graspy\__init__.py", line 3, in <module>
    import graspy.cluster
  File "C:\Users\user\Miniconda3\envs\untitled1\lib\site-packages\graspy\cluster\__init__.py", line 3, in <module>
    from .autogmm import AutoGMMCluster
  File "C:\Users\user\Miniconda3\envs\untitled1\lib\site-packages\graspy\cluster\autogmm.py", line 20, in <module>
    from sklearn.mixture.gaussian_mixture import (
ModuleNotFoundError: No module named 'sklearn.mixture.gaussian_mixture'

```

## Your Environment
* Python version: 3.8
* mvlearn version: 0.4.0

**Comment by agramfort** [comment]
@lkrmbhlz the bug is in graspy not in mvlearn. https://neurodata.io/graspy/ AFAIK

**Comment by lkrmbhlz** [comment]
@agramfort Thanks for the quick reply. 🙂 I only assumed it was due to mvlearn because when I downgrade to sklearn 0.22, it works perfectly fine! Unfortunately, I need a newer sklearn version in my project for other reasons.

**Comment by rflperry** [comment]
Yep, the graspy dependency was ported over to a newer [graspologic](https://pypi.org/project/graspologic/) package and so has stopped being maintained; this needs to be updated here accordingly. For now, the simplest solution besides downgrading sklearn is installing mvlearn locally and not installing the graspy dependency, see here https://pypi.org/project/graspologic/.
