### ISSUE TITLE
multiview ranking

### ISSUE THREAD

**Issue by arita37** [mvlearn/mvlearn#298]
Hello,
Thanks for the package.
Just wondering if you plan to integrate multiview ranking.

Example   :  
   3 ranking on same list of items.
           Ra : ra,1.      ra10, ...
           Rb : rb,1.     rb10, ...
           Rc : rc,1.     rc10, ...
     
    How can we compare them or merge them ?
    thanks

**Comment by rflperry** [comment]
I'm unfamiliar with multiview ranking and I'm not sure if this package is the right place for it. Indeed it doesn't strike me as a multiview problem as it can be represented by a single 2D matrix. No plans to implement, so will close the issue.
