### ISSUE TITLE
sample_joint_factor_model in CCA Tutorial 

### ISSUE THREAD

**Issue by mmosc** [mvlearn/mvlearn#301]
## Expected Behavior
In the [CCA Tutorial](https://mvlearn.github.io/auto_examples/embed/plot_mcca_tutorial.html), ```sample_joint_factor_model``` should return a list of matrices ```Xs``` and two additional matrices ```U_true``` and ```Ws_true```.  

## Actual Behavior
It returns only three matrices (i.e. the list of matrices Xs) instead. This causes problems in the remaining of the tutorial.

## Solution
Add ```python return_decomp=True``` to ```python sample_joint_factor_model```.
```python
Xs1, U_true, Ws_true = sample_joint_factor_model(
    n_views=n_views, n_samples=n_samples, n_features=n_features,
    joint_rank=joint_rank, m=5, noise_std=1, random_state=23,
                return_decomp=True
)
```

**Comment by gavinmischler** [comment]
Sorry has this been resolved? In the current tutorial it looks like return_decomp is set to True

**Comment by mmosc** [comment]
Looks like it, thanks!
