### ISSUE TITLE
Graspy/Graspologic dependency change

### ISSUE THREAD

**Issue by gavinmischler** [mvlearn/mvlearn#305]
## Current Issue

The fact that mvlearn still depends on graspy, which is no longer being maintained, has caused several issues:
Issue #275 #294 #296 

I started working on a dependency switch from graspy to graspologic, but the problem is that graspologic is not on conda-forge. Currently, conda-forge requires all dependencies be on conda-forge. 

I am wondering if the best option is to simply remove Graspy/Graspologic as a dependency altogether. It would reduce the dependency graph and remove any potential future problems where issues with Graspy or its dependencies cause issues in mvlearn. Graspy is currently only used to support mvlearn.embed.Omnibus, which is basically just a wrapper of graspy.embed.OmnibusEmbed. So, removing Graspy would only remove a single class which does not provide any additional value being in mvlearn, since it is already implemented elsewhere with essentially the same API. 

## Proposed Solution

Remove the Graspy dependency from both pip and conda installations, along with mvlearn.embed.Omnibus class.

## Additional Thoughts

We could also keep the shell of the Omnibus class for the next release so if a user tries to import it they are given a message that the class is depracated and they can find the same functionality in graspologic.embed.OmnibusEmbed

**Comment by agramfort** [comment]
+1 to remove it
